version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: api-vendas
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: api-vendas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
